package api

const (
	// Common
	FAILED_DECODE_DATA       = iota + 1
	FAILED_GET_SETTINGS      //2
	HAVENT_RIGHTS_FOR_ACTION //3
	FAILED_ENCODE_DATA       //4
	END_POINT_NOT_FOUND      //5
	INVALID_TOKEN            //6
)

// Chat API
const (
	CREATED_CHANNEL           = iota + 1
	USER_CHAT_CHECK_FAILED    //2
	USER_IS_DELETED_FROM_CHAT //3
	FAILED_GET_USER_INFO      //4
	FAILED_GET_USERS_FOR_ADD  //5
	FAILED_DELETE_USERS       //6
	FAILED_RECOVERY_USERS     //7
	FAILED_GET_CHAT_SETTINGS  //8
	SHORT_CHAT_NAME           //9
	FAILED_SET_NAME_CHAT      //10
	FAILED_DELETE_FROM_LIST   //11
	CREATED_CHAT              //12
)

//File API
const (
	FAILED_DECODE_FORM_DATA   = iota + 1
	FAILED_GET_DATA_FROM_FORM //2
	FAILED_REBUILD_DATATYPES  //3
	FAILED_CREATE_FILE        //4
	FAILED_OPEN_FILE          //5
	FAILED_DELETE_FILE_DB     //6
	FAILED_DELETE_FILE_OS     //7
	FILE_DOESNT_EXIST         //8
)

//Messages API
const (
	FAILED_GET_ADDITIONAL_MESSAGES = iota + 1
	FAILED_GET_MESSAGES            //2
)

//User API
const (
	FAILED_GET_USER       = iota + 1
	FAILED_GENERATE_TOKEN //2
	SOME_EMPTY_FIELDS     //3
	FAILED_CREATE_USER    //4
	FAILED_GET_USER_CHATS //5
	FAILED_SET_SETTINGS   //2
)
