package api

// Common
const (
	FAILED_DECODE_DATA = iota + 1
)

// Chat API
const (
	SHORT_CHAT_NAME = iota + 2
	INVALID_TOKEN
	CREATED_CHAT
	CREATED_CHANNEL
	USER_CHAT_CHECK_FAILED
	USER_IS_DELETED_FROM_CHAT
	FAILED_GET_USER_INFO
	FAILED_GET_USERS_FOR_ADD
	HAVENT_RIGHTS_FOR_ACTION
	FAILED_DELETE_USERS
	FAILED_RECOVERY_USERS
	FAILED_GET_CHAT_SETTINGS
	FAILED_ENCODE_DATA
	FAILED_SET_NAME_CHAT
	FAILED_DELETE_FROM_LIST
	END_POINT_NOT_FOUND
)
